---
title: "Prelude to Level One"
author: "By Hellen Gakuruh"
date: "January 18, 2017"
output: html_document
---

First welcome to level one of **Data Analysis using R**. This level aims to introduce both **R** - the core/base program and **RStudio** - a program that makes programming easier (Integrated Development Environment - IDE).

We will begin by downloading and understanding both R and RStudio including how to work interactively using the **console** and writing **scripts** (similar to syntax in SPSS and "do-files" in STATA). We shall further discuss how to install and work with add-on programs called **packages**. 

With the basics of how to start, work and close R and RStudio done, we shall venture into the most important knowledge or skill you need to have in order to do any data analysis in R, this is **making function calls** or simply issuing commands.

Later we shall get to know how to manage different versions of your documents like scripts using a **version control system** called **Git** and how to freely store/share the documents online using **GitHub**. This shall become quite handy when you make changes on your document or collaborate with others.

Next we shall explore **R's data types and objects** and how to **transform and manipulate** them. We shall also see how to **import and export data** from or into various other programs. 

Since time series analysis is a critical data analysis technique, understanding how R works with **dates and time** is crucial and a session on this shall also be covered.

As we wind-up this level, we shall have a glimpse of R's wonderful world of **graphics**, something this program is revered on. We shall also discuss how and where to **get help**. Finally we shall conclude with **case studies** covering most of the areas discussed as a way to cement knowledge and skills covered. 

It's my hope that by close of this level you will have the ability to work with R and be ready for data analysis.

### Session Goals
  
* Get to know R and RStudio
* Make function calls
* Acquaint yourself with version control systems 
* Know data types and objects used in R
* Learn how to import and export data
* Be able to Transform/Manipulate different data objects including Subsetting them 
* Know how to working with R's date and time
* Have a feel of base R's graphing capabilities
* Know where and how to get help
* Apply lessons learnt through Case Studies
