---
output: 
   html_document:
      css: pages.css
---

# Blogs
## Hellen Gakuruh

### Blog30: July 14^th^, 2017

<h4 style="font-weight:bold">Appendix 1 now on GitHub and on website</h4>

Appendix 1 is now uploaded on [GitHub](https://github.com/HellenG/Data_Analysis_Book) and on my [website](https://helleng.github.io/Data_Mgt_Analysis_and_Graphics_R/Data_Analysis/index.html). I hope it is an enjoyable read as it was an enjoyable writing process. Getting to do this mathematics has been quite fulfilling and I hope to take up a bit more algebra just to grasp it even better.

This week I got to apply a bit of that mathematics to color Venn diagrams. I have completed it and will be uploading it in a short while. 

Our next chapter is "Probability" which I look forward to write, so keep checking for updates on it's development.

From me it is a good weekend (I will definitely be working) and a fruitful week ahead.

### Blog29: July 7^th^, 2017

<h4 style="font-weight:bold">Mission accomplished</h4>

In deed, I am super excited to say appendix 1 on re-introduction mathematics is done. Well at least zero draft which is core part of this writing process. What is left now is to make it draft 1 which would be ready for uploading. I am currently working on this and should be done by Monday if all things remain constant. I am sure I will be uploading this chapter as I make this blog live, so check it out. 

With that, from me it is a good weekend (I know I will be working half of it) and do have an extremely productive week ahead.


### Blog28: June 30^th^, 2017

<h4 style="font-weight:bold">Winding down section on derivatives</h4>

Quite an interesting week and again I discover how important it is for me to finish this chapter on refresher mathematics and do it well. I am up to speed with intended write-up as I am now winding up on derivatives. If all goes well I should start Integration early next week, hence I can see end in sight.

Given this fact, I do expect to be working through the weekends until zero draft is out. Looking forward to a productive session until this is achieved.

With that I wish you a fantastic weekend and as usual, a very productive week ahead. 

### Blog27: June 23^rd^, 2017

<h4 style="font-weight:bold">Joy that is math and graphing functions in R</h4>

Mathematics can be quite enjoyable especially when you do it in R. Though sometimes coding some of these graphs have been quite a (good) challenge, shear joy of seeing its final output is enough to want to do more. So looking forward to more graph development.

I have reached second derivative and was actually hoping to clear it by tonight but this seems to take another angle. But I am eager to wind it up and move to curve sketching and just a bit more on derivatives especially on logs and exponents. Once this is done then I can embark on our topic of interest, integration.  

With this past weeks I have come to realize how important it is for me to do this chapter and to do it well, events playing out right now sure indicate this is a deal changer and for that I am super geared to make it happen at whatever cost.      

Tomorrow I take some time off but working on Sunday as usual.

From me it's a good weekend and here's to hoping and wishing for an uneventful yet productive week ahead.

### Blog26: June 16^th^, 2017

<h4 style="font-weight:bold">Good week leads to good outputs</h4>

It was a good week and truly appreciative even with minor glitches here and there; overall it was a great improvement. And just to show how good it has been, I was able to make some polynomials which you might recall had given me a bit of a (good) challenge.

Currently I am working on derivatives and graphs, if all goes well, I should wind up with this section next week and embark on integration. 

Here's to a good (working) weekend and a goal oriented week ahead.

### Blog25: June 9^th^, 2017

<h4 style="font-weight:bold">Eventful week leads to renewed zeal</h4>

Quite an eventful week this has been. But with it, I have gained a lot of zeal and momentum to finish this chapter. I think I have not wanted something as bad as this, I am more than determined to make this happen, so watch this space, IT'S ON.

As regards progress, I am still doing derivatives and really enjoying it's little bumps, like right now I am trying to graph a polynomial which has seen me go back to add a section on factoring polynomials (part of basic Algebra) which for some reason I did not include earlier. I can't wait to see this graph just like I can't wait to integrate area under a curve. But all good things come to those who persist.

Do have a fun and fruitful weekend as well as a highly productive week ahead.

### Blog24: June 2^nd^, 2017

<h4 style="font-weight:bold">Derivatives and all things Calculus</h4>

So this week saw my start of Calculus and specifically Derivatives. I got a small bump figuring out a certain concept and how to convey it in my write-up. I have since passed it and moving along nicely. I do not intend to go into greater depth on this topic as this is only meant to serve as a foundation for Integration.

Doing my best to have this section completed by next week and embark on Integration immediately.   

Given yesterday was a public holiday which I allowed myself to be off, this will be a working weekend with usual weekend working hours.

Here's to a fruitful weekend and a super great week ahead.

### Blog23: May 26^th^, 2017

<h4 style="font-weight:bold">Pre-calculus is finally done</h4>

Off to a good start after completing pre-calculus. I am currently winding up with introduction to limits and will embark on "Derivatives" early next week. Enjoying refreshing on these mathematical concepts and hope it comes across in my write-up. Still keeping my eye on our goal, "determining area under a curve" which is covered by integration.

From me, do have a lovely weekend and a productive week ahead.

### Blog22: May 19^th^, 2017

<h4 style="font-weight:bold">Still working on pre-calculus but making progress</h4>

Well I underestimated content of Elementary Functions, still finalizing this section and should embark on Calculus next week. Do intend to work though the weekend all things remaining constant.

Till next week, have a fantastic weekend and week ahead.

### Blog21: May 12^th^, 2017

<h4 style="font-weight:bold">Behind schedule but it's all system work</h4>

Due to unforeseen and unavoidable circumstances, I was not able to put in some good hours last weekend, so my expectations of covering up time out was not achieved. However, I do intend to work through this weekend and see if I can get this chapter moving along some more.

In my last post I did not factor in an important mathematical concept leading to calculus, that is "Elementary Functions". I have added this to our mathematics appendix and currently writing on "Graphs and Transformations". This is the last section before I begin calculus, so hopefully if all goes well, I should embark on calculus early next week. I do not intend it to be intense, just enough basics to work with probability.

Till next week, do have a wonderful weekend and week ahead.

### Blog20: May 5^th^, 2017

<h4 style="font-weight:bold">A tad behind schedule but making good progress</h4>

As a last minute decision I decided to take last weekend off as well as Monday which was a holiday (Labor day). As it turned out, this was a great decision as I totally rested, however that meant my schedule would be altered. I had anticipated to finish pre-calculus math sometime this week but this was not to be. To address this, I intend to work through this weekend.

If all goes well, I should start elements of functions this weekend or early next week and then proceed on to calculus. 

Till next week, have a good one.

### Blog19: April 28^th^, 2017

<h4 style="font-weight:bold">In-person training and Book progress</h4>

This week I have been conducting an on site training on a different area (M&E). It sure has been great doing this. Saturday I managed to do my first in-person training on Introduction to R, it was quite quick but hope next time to do a full length training.

Appendix one on Mathematics is progressing well though due mentioned activity, not much has been done this week. However, I pick up from where I left off (linear equations) as from tomorrow. I am not too sure what to expect when doing actual calculus but do expect it to take about two weeks hence expected time of delivery should be around the week of 12th May all things remaining constant (ceteris paribus). 

### Blog18: April 21^st^, 2017

<h4 style="font-weight:bold">Good progress on Refresher Mathematics Chapter and doing initial "R Essentials" in-person training</h4>

I have made good progress in Refresher mathematics, I am now left with three important topics: Linear and Quadratic equations as well as Calculus. 

I am doing a small training tomorrow, so I have to prepare for that. However, this will not deter current development being made in mathematics.

Till next week, have a wonderful weekend and week ahead.

### Blog17: April 14^th^, 2017

<h4 style="font-weight:bold">Holiday wishes and EDA progress</h4>

Easter holiday is here, today is Good Friday a time to reflect on sacrifices made by those who care for us. I wish you good day and weekend, do take time to enjoy it if you intend to also work like me.

EDA has began well, though I am still not sure I should have put it right after descriptive statistics and not after inferential statistics as some of the approaches need some basic understanding of assumptions made by inferential statistics. Anyway, I will gauge how much to present at this point and if it becomes difficult to discuss a lot of sections due to prerequisite knowledge, I will switch it with chapter four. Should be able to disclose this on next blog post. Time-wise I think I am doing okay though I feel am getting to a point where I might spend a little bit more time per sub-section.

From me, have a good Friday, till next week.


<u>Update 15th April, 2017</u>

Happy Easter Saturday, it's a beautiful day to do some bit of works, won't you agree?

I have decided to pause EDA  as it has become clear it would not be possible to discuss using EDA for model building without knowledge of some basic models. Since most of the models are discussed in later chapters beginning with inferential, then it's prudent to discuss these first.

With that, I will embark on refresher mathematics (essential math for inferential statistics) and then proceed with Inferential Statistics Chapter. Kinda looking forward to a bit of math as I have truly become quite rusty. Our goal here is to be able to compute area under a curve using integration. 

Okay, let's have some fun.

### Blog16: April 4^th^, 2017

<h4 style="font-weight:bold">New look and EDA is on course</h4>

Yet another good but fast week; it feels like I was posting my last update yesterday. 

On good progress, [Data Mania](https://helleng.github.io/Data_Mgt_Analysis_and_Graphics_R/) has a refreshed look, nothing to blow the horn for, but still, it's some change. I still maintain on coding rather than using a template, hope it communicates and you can move around the site.

I have started EDA though for most of this week and next, I will be refreshing my knowledge, hence anticipate to start write-up week starting 17 April 2017. Expected time for release is 23rd April 2017 all things remaining constant.

Till next (good) Friday (yes I will be working), have a fantastic weekend and a good week ahead. 

### Blog15: March 31^st^, 2017

<h4 style="font-weight:bold">Slides are officially out and made first YouTube upload</h4>

Good week it was, managed to complete all slides, currently I am doing final edit and pushing to GitHub. Links to html versions are listed in [tutorials page](Pages/tutorials.html), I also intend to convert these slides to PDF and share on "Slideshare".

Great achievement, did my first YouTube video, not much really, but it means I can actually do more and hopefully improve on quality.

With Slides over, it's time to go back to finalizing "Essentials of Data Analysis and Graphics using R" book, specifically start working on chapter three "Exploratory Data Analysis (EDA)". Can't give exact time for release but anticipate it to be in two weeks from start. I should have a good idea by Friday.

Till next Friday, have a fantastic week.

### Blog14: March 24^th^, 2017

<h4 style="font-weight:bold">Going the extra mile</h4>

So I am way behind schedule, but it's all good as a lot of what I am doing will shorten time spent writing chapter on inferential statistics. I am going the extra mile to ensure all the essentials are covered and covered well (I was a bit rusty). 

Looking forward to creating colorful graphs during EDA chapter, so I will try to wind this up.

Sadly I did not get to teach this week but will strive to get at least one in-person training this quarter. Otherwise, I am thinking of YouTube sessions and some webinar's, they are actually way overdue.

Till next week (hopefully slides will be out), it's good weekend and good week from me. 

### Blog13: March 17^th^, 2017

<h4 style="font-weight:bold">Almost done and might be teaching next week</h4>

Doing final write-up on slides to "Introduction to Data Analysis and Graphics using R". It's been enjoyable refreshing on these essential concepts and look forward to start EDA.

I might be teaching next week, something I truly enjoy, so EDA might delay slightly, but it's all good, I will definitely get around to it.

Till next week, but do look out for my slides, I have tried to make them comprehensive, at least to presentation level. If you do attend one of my classes, let's have some fun learning.  
  

### Blog12: March 10^th^, 2017

<h4 style="font-weight:bold">Making presentations and looks like a summarized R-Essentials is in progress</h4>

A great week it was. I have managed to do three slides out of six and currently winding up on the fourth. I anticipate to have them out by end of next week.

As I write these slides, it's occurred to me I am actually writing a summarized version of "R-Essentials". This is great as I had hoped to write summarized/reference book once I am done with the three books. Guess I am up to speed on that one.

Well, till next week when I share the slides and prepare for EDA chapter.

###  Blog11: March 4^th^, 2017

<h4 style="font-weight:bold">Yap it's Out, next, presentations</h4>

Truly pleased to say Descriptive statistics is finally done (except for exercises) and it's out. Had a great time refreshing on these topics and looking forward to chapter 3. 

I will take sometime to prepare some slides for upcoming workshop so I anticipate chapter three to come out slightly later this month, but let's see next week what I will be up to and how much needs to be done. 

### Blog10: February 24^th^, 2017

<h4 style="font-weight:bold">Making progress and anticipate some change to index page</h4>

Progressing well with Chapter two and anticipated time to get it out is still feasible. Bulk of the concept is done with just a bit of formulas definition left. I will soon start on our case study as a wrap-up for this chapter.

Currently there is no changes made on index page, but I am optimistic some change will take place pretty soon. 

### Blog9: February 17^th^, 2017

<h4 style="font-weight:bold">Slight change on index page, upcoming blogdown package and making progress with chapter two</h4>

I have just made some slight changes on our index page, it's still a work-in-progress, but hopefully I will get a bright idea of how to redesign it using code. It is important for me that this page remains a pure HTML/CSS file as it demonstrates my skills in these two languages. 

A week or so ago I learnt of a new package called "blogdown", it's still under (advance) development but I am certainly anxious to try it. However, I am holding it off at least until I wind-up with this current write-up but I certainly look forward to learn it. I think, just like "bookdown", I will add a section of it in our second book "R - Beyond Essentials" as one way for analysts and R programmers to document.

This week I have concentrated on writing chapter two, "Descriptive statistics" and realized how much there is to basic statistics. I am writing this chapter knowing it is a crucial foundation on which all other statistics are based on. I have managed to write quantiles and measures of central tendency, am currently working on measures of dispersion and then move on to skewness and kurtosis and finally run through a case study. Holding all things equal (ceteris paribas), I estimate another two weeks for this chapter to come out.

P.S. I was thinking about the title of our third book, would "Essentials of Data Analysis and Graphics using R" sound okay or would it be too much essentials? It could be an essentials series, anyway, it's just a thought and I will make my final decision once I am done writing the whole book.

### Blog8: February 10^th^, 2017

<h4 style="font-weight:bold">Released Chapter One, Changed book's name and still working on Descriptive statistics</h4>

Introductory chapter of our third book is out, you can read it at this [page](../Data_Analysis/index.html). In this chapter I discuss a few terms as well as book structure. There some substantial changes in writing approach and topics to be covered; for one, in all the chapters (except chapter one), we shall begin with concept then demonstrated it's application using R. We shall also have a section on applicable graphs including a plotting session in R. At the end of each chapter, we will go through a brief case study covering concepts learnt in that chapter. This case study will conclude with a sample (partial) report showing how to report findings. Reason for taking this approach is because this is what I would have loved reading when I started data analysis.     

While writing Chapter one, I realized there quite a number of sections that go beyond an introductory session, in actual fact, my new approach for writing this book does not fall under introduction. For this reason I have changed the title of our third book to "Fundamentals of Data Analysis and Graphics using R". Hopefully during the weekend I will get around to changing the book cover.

As a result of this (out of the blues) change, I am a tad behind schedule with Descriptive statistics. But it's all good because this new approach makes me work extra hard to deliver a good read for anyone interested in data analysis. 

By the way, [Indepth Research Institute](http://www.indepthresearch.org/) is going to host a training Course on Data Management, Analysis and Graphics with R on: 20-03-17 and 10-04-17. Please visit [this](http://www.indepthresearch.org/research/project-management-monitoring-and-development-evaluation/2956-training-course-on-data-management-analysis-and-graphics-with-r) site for more details and consider attending the training, I will be facilitating.

One final word, I have just created an [issues page](https://github.com/HellenG/Data_Mgt_Analysis_and_Graphics_R/issues/1) for any improvement on "R Essentials" book. I would truly appreciate any enhancement for our book.

Till next Friday 

### Blog7: February 3rd, 2017

<h4 style="font-weight:bold">Book Release, Web Changes and Delay in Starting Descriptive Statistics Session</h4>

I am pleased to say I have managed to turn all tutorials for level one into an E-book titled ["R Essentials"](../R_Essentials/index.html) thanks to a new R package called [bookdown](https://www.rstudio.com/resources/webinars/introducing-bookdown/). This transition from session notes to a book will make it easy to read and follow through each concept. Level two and three notes will also become books with level two titled "R - Beyond Essentials" and level three "Introduction to Data Analysis and Graphics using R". I intend to release each chapter of as soon as I am through with them, so look out for updates.

Our E-book is hosted by [GitHub pages](https://help.github.com/articles/what-is-github-pages/) and I have been spending quite a bit of time trying to build the website. All pages are written with [Rmarkdown](http://rmarkdown.rstudio.com/) except index/first page which I decided to code. My reason for doing this is to refresh on my HTML and CSS skills; it is not perfect and I certainly don't like the background so much but it's a start and I do hope to improve it with time. Take a [look](http://helleng.github.io/Data_Mgt_Analysis_and_Graphics_R/) and let me know.   

With my little detour to create an e-book and improve our tutorial website, scheduled start of "Descriptive Statistics" has been pushed forward (a bit). I do however intend to have it ready in the next two weeks (if not earlier), so not to worry, it's all good and I am hard at work.

One final word, I do intend to make it a habit to make a blog post every Friday just to keep you updated on progress I am making as regards tutorial notes (book chapters). This way there is an account of what is happening and if I make any necessary detour, then we will all be on the same page.

### Blog6: January 20, 2017

<h4 style="font-weight:bold">Alternating development and release of Level Two and Three</h4>

With Level One complete, we have the skills to carryout data analysis in R. Level two is meant get a bit deeper in R by learning how to develop functions and packaging them ready for GitHub/CRAN. However, it is not necessary to have these skills before doing data analysis. 

Therefore we will begin with data analysis sessions in Level Three but stop every after one session to introduce some concept in level two. That way we have both level two and level three tutorials moving in tandem.

Our next session is "Introduction to Descriptive Statistics" (session sixteen). Look out for it.

### Blog5: January 18, 2017

<h4 style="font-weight:bold">Draft version of Level One is now complete</h4>

Truly please to say Level One is now complete, it's been quite a journey to get here, but it is done and you can read it all from [notes and presentations page](tutorials.html). These notes can also be downloaded from my [LinkedIn page](https://ke.linkedin.com/in/hellengakuruh).

Good Reading


### Blog4: July 13, 2016

<h4 style="font-weight:bold;">Session Eight: Plotting in Base R</h4>

"There is so much to basic base R".

Base R offers so much it only requires knowledge of what is there and how you can fine tune it; more so as regards plotting.

As you embark on this session, I want you to think of three scenarios, first an analyst who has presented a very good report with graphs; second, an analyst who presents a good report along side a very long script, third an analyst who presents a well written report with communicative graphs, a well thought out, adequately commented and reproducible script along with data used. Given your introduction to R knowledge, whose work would you prefer and why?  


### Blog3: Thursday, May 26, 2016

<h4 style="font-weight:bold;">Technical Glitch</h4>

Well, I experienced what they call "a technical glitch" while trying to build my site (https://github.com/HellenG/HellenG.github.io). For some reason I am not getting the pages to work: I wonder where my "html" knowledge went to.

Anyway, I intend to address this very soon, but for now, the notes (for session one, two and four) can be forked from the tutorial's repo "https://github.com/HellenG/Data_Mgt_Analysis_and_Graphics_R"

Good reading



### Blog2: Saturday, May 21, 2016

<h4 style="font-weight:bold;">Session One of Level One Released</h4>

The long wait is finally over; first session of the "Data Analysis using R" is now ready and uploaded. Please check my [tutorial site](https://HellenG.github.io/Data_Mgt_Analysis_and_Graphics_R) and have a read.

Still working on the demo's and other links, but they will up and running in no time.

Enjoy


### Blog1: Friday, January 22, 2016

<h4 id="Title" style="font-weight:bold;"> My upcoming tutorial series on "Introduction to Data Analysis Using R"</h4>

I am about to start a data analysis tutorial using R. This will be a series of gradual learning centered at introducing data analysis and R. If you have thought of learning some analysis or R, come along and learn with me. 

<h4> Who is the training for?</h4>

This training is aimed at anyone interested in transforming readily available data into insightful information as well as those interested in reproducible analysis.

It is most suitable for those new to data analysis and R. 

<h4> What will you need?</h4>

All you need for this tutorial series is a working computer with about 150mb of disk space for the installation of R. You will of course need internet to download the slides.

But above all, you will need a great amount of interest and an open mind.

<h4> What will you learn?</h4>

The main goal of this tutorial is to enable you to use R for data analysis. The tutorial is divided into three levels. The first level will give you the foundation, while the second level delves right into R's core which is programming and level three will impart the core knowledge and skills of this tutorial series which is data analysis. Level two is optional but highly recommended for effective and efficient coding in R. 

Each level is divided into a series of sessions aimed at giving you a gradual learning structure. Below is the general outline: 

<u> Level 1: Main goal is to introduce R and R's graphics</u>

Here is what we will learn:

* SessionOne: Get to know R and RStudio
* SessionTwo: Make function calls
* SessionThree: Acquaint yourself with version control systems 
* SessionFour: Know data types and objects used in R
* SessionFive: Learn how to import and export data
* SessionSix: Be able to Transform/Manipulate different data objects including Subsetting them 
* SessionSeven: Know how to working with R's date and time
* SessionEight: Have a feel of base R's graphing capabilities
* SessionNine: Know where and how to get help
* SessionTen: Apply lessons learnt through Case Studies

<u>Level 2: Main goal is to learn how to Programming in R</u>

This is what we will be learn:

* SessionEleven: Looping System in R
* SessionTwelve: Environments
* SessionThirteen: Introduction to function development
* SessionFourteen: Reproducible Analysis in R (Rmarkdown, Bookdown and Shiny) 
* SessionFifteen: Package Development

<u>Level 3: Main goal is to introduce principle concepts and methods of Statistics</u>

Here is what We will learn:

* SessionSixteen: Introduction to Descriptive Statistics
* SessionSeventeen: Introduction to Exploratory Data Analysis (EDA) 
* SessionEighteen: Introduction to Inferential Statistics
* SessionNineteen: Introduction to Categorical Analysis
* SessionTwenty: Introduction to Time Series Analysis
* SessionTwentyOne: Introduction to Survival Analysis

<h4> Approach used</h4>

Level one is geared towards introducing R and preparing for the real application. This is a requirement for the rest of the tutorial as the core foundation of R is introduced. In this level, you get to appreciate that data need not be survey data that is usually collected for inference. It can be data that can be easily sourced from everyday activity. For example income generated from services rendered or data from training exercise monitors. The idea is that analytical literacy is essential in turning readily available data into useful knowledge.

Level two is meant to impart some programming skills for those interested in going beyond simple analysis. The skills learnt in this level will aid in developing user defined functions. If your goal is to learn how to use R to do basic analysis, then you can skip the second level and only refer to it as need be.

Actual application or analysis begins at level three. In this level, you get to learn data analysis from descriptive to inferential statistics using survey data. At this point the assumption is that you know how to use one of the statistical programs and more so R. So the discussion will be on the analysis rather than the codes used to do the analysis.   

<h4> Becoming an R'st</h4>

The biggest question anyone will eventually ask you as you work with R is, 'Why R?'. Indeed, R is one of the many analytical tools, and the key word here is "a tool". So why select it as your analytical tool and not another? I will leave you to answer that question after you have worked with R for some time.

But what I can tell you, R grows on you. At first it might seem a bit different and if you are not well grounded, you might find it difficult in the beginning. As time goes by and you interact with R, learning and using its vast capabilities, you start getting used to it. I personally think its growing usage and most importantly the increasing innovations and packages (add-on), is a big indicator as to where R is headed. For example, the notes as well as the power point presentations are all done using R; there is no need to open text documents and copying your code in it. There are also web apps (applications) like Shinny that you can use to build online analytical applications. But what R is best known for, is its graphing capabilities and a lot of analysts use R for their graphs. Well, I could go on, but it would be good for you to experience R and make your recommendations.

As a new user of R, my strongest advice (based on experience), is to get the basics right. The issues we shall soon be discussing like data types, objects, workingspace, getting help, etcetera, are key to becoming a good R user or programmer. In addition to this tutorial, I recommend you join some of the well known online courses like DataCamp, swirl as well as Coursera's data science specialization. YouTube also has very good lecture series on R and lastly but definitely not the least, I recommend the good old fashioned way of learn anything - reading an R textbook. In addition, try and do as many exercises as you can from these resources, or go to the help pages like the R mailing group and try to figure out solutions for areas you have covered then assess your progress with solutions offered. This will gain you a substantial mileage as far as R programming is concerned.

Of course I cannot fail to mention that R is completely free, and maintained by passionate people. It has its shortcomings, but in every one of them, there is someone somewhere driven by sheer desire to solve the problem, so you would find that the solution to any of the shortcomings has been addressed or is on the pipeline to being solved.

It is therefore my hope that these tutorials will create more r users or what I fondly call R'sts. I believe anyone can learn to code if they are given a good foundation and no assumptions are made. So code away and become a budding analyst or R'st.

<h4>Fee</h4>

This is a free online course. But feel free to support this noble venture.
