---
title: "Prelude to Level Three"
author: "Hellen Gakuruh"
date: "January 19, 2017"
output: 
   html_document:
      css: ../../pages.css
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

Welcome to level three, this is the core of this tutorial series. It is aimed at giving you a good foundation in Statistics; that is, the fundamental concepts and methods in Statistics. In all the sessions, we will get to understand the reasoning behind the calculations including assumptions made thereby giving us the ability to make sound interpretation of results. 

In this level, we will begin by learning how to describe data before learning how to make inferences and predictions from the data. 

Specifically we will cover:

* SessionSixteen: Introduction to Descriptive Statistics
* SessionSeventeen: Introduction to Exploratory Data Analysis (EDA) 
* SessionEighteen: Introduction to Inferential Statistics
* SessionNineteen: Introduction to Categorical Analysis
* SessionTwenty: Introduction to Time Series Analysis
* SessionTwentyOne: Introduction to Survival Analysis










